# Generated by Django 3.2 on 2023-11-29 18:23

from django.db import migrations, models
import django.db.models.deletion
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Внести название', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Внести идентификатор', max_length=256, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'объект категории',
                'verbose_name_plural': 'Категории',
                'ordering': ('name', 'slug'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Внести название', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Внести идентификатор', max_length=256, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'объект жанра',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name', 'slug'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenreToTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(help_text='Внести жанр', on_delete=django.db.models.deletion.CASCADE, to='reviews.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Внести название', max_length=256, verbose_name='Название')),
                ('year', models.IntegerField(help_text='Внести дату выпуска', validators=[reviews.models.validate_for_year], verbose_name='Дата выпуска')),
                ('description', models.TextField(blank=True, help_text='Внести описание', null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Внести категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(help_text='Внести жанр', through='reviews.GenreToTitle', to='reviews.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='genretotitle',
            name='title',
            field=models.ForeignKey(help_text='Внести название', on_delete=django.db.models.deletion.CASCADE, to='reviews.title', verbose_name='Название'),
        ),
    ]
