# Generated by Django 3.2 on 2023-11-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretotitle',
            options={'ordering': ('title',), 'verbose_name': 'связь медиа с жанром', 'verbose_name_plural': 'Связи медиа с жанрами'},
        ),
    ]
