# Generated by Django 3.2 on 2023-11-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_genretotitle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Рейтинг'),
        ),
    ]
