# Generated by Django 3.2 on 2023-12-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231201_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id', 'name', 'slug'), 'verbose_name': 'объект категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-id', 'name', 'slug'), 'verbose_name': 'объект жанра', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='genretotitle',
            options={'ordering': ('title', 'genre'), 'verbose_name': 'связь медиа с жанром', 'verbose_name_plural': 'Связи медиа с жанрами'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-id', 'name'), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
